src/dashboard/src/fpr/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url

from fpr import views

UUID_REGEX = r"[\w]{8}(-[\w]{4}){3}-[\w]{12}"

app_name = "fpr"
urlpatterns = [
    url(r"^$", views.home, name="fpr_index"),
    url(
        r"^(?P<category>format|formatgroup|idrule|idcommand|fprule|fpcommand)/(?P<uuid>"
        + UUID_REGEX
        + ")/toggle_enabled/$",
        views.toggle_enabled,
        name="toggle_enabled",
    ),
    # Formats
    url(r"^format/$", views.format_list, name="format_list"),
    url(r"^format/create/$", views.format_edit, name="format_create"),
    url(r"^format/(?P<slug>[-\w]+)/$", views.format_detail, name="format_detail"),
    url(r"^format/(?P<slug>[-\w]+)/edit/$", views.format_edit, name="format_edit"),
    # Format Versions
    url(
        r"^format/(?P<format_slug>[-\w]+)/create/$",
        views.formatversion_edit,
        name="formatversion_create",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        views.formatversion_detail,
        name="formatversion_detail",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/edit/$",
        views.formatversion_edit,
        name="formatversion_edit",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/delete/$",
        views.formatversion_delete,
        name="formatversion_delete",
    ),
    # Format groups
    url(r"^formatgroup/$", views.formatgroup_list, name="formatgroup_list"),
    url(r"^formatgroup/create/$", views.formatgroup_edit, name="formatgroup_create"),
    url(
        r"^formatgroup/(?P<slug>[-\w]+)/$",
        views.formatgroup_edit,
        name="formatgroup_edit",
    ),
    url(
        r"^formatgroup/delete/(?P<slug>[-\w]+)/$",
        views.formatgroup_delete,
        name="formatgroup_delete",
    ),
    # ID Tools
    url(r"^idtool/$", views.idtool_list, name="idtool_list"),
    url(r"^idtool/create/$", views.idtool_edit, name="idtool_create"),
    url(r"^idtool/(?P<slug>[-\w]+)/$", views.idtool_detail, name="idtool_detail"),
    url(r"^idtool/(?P<slug>[-\w]+)/edit/$", views.idtool_edit, name="idtool_edit"),
    # ID Rules
    url(r"^idrule/$", views.idrule_list, name="idrule_list"),
    url(r"^idrule/create/$", views.idrule_edit, name="idrule_create"),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.idrule_edit,
        name="idrule_edit",
    ),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/$",
        views.idrule_detail,
        name="idrule_detail",
    ),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.idrule_delete,
        name="idrule_delete",
    ),
    # ID Commands
    url(r"^idcommand/$", views.idcommand_list, name="idcommand_list"),
    url(r"^idcommand/create/$", views.idcommand_edit, name="idcommand_create"),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/$",
        views.idcommand_detail,
        name="idcommand_detail",
    ),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.idcommand_edit,
        name="idcommand_edit",
    ),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.idcommand_delete,
        name="idcommand_delete",
    ),
    # FP Rules
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/$",
        views.fprule_detail,
        name="fprule_detail",
    ),
    url(r"^fprule/create/$", views.fprule_edit, name="fprule_create"),
    url(r"^fprule/$", views.fprule_list, name="fprule_list"),
    url(r"^fprule/(?P<usage>[-\w]+)/$", views.fprule_list, name="fprule_list"),
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.fprule_edit,
        name="fprule_edit",
    ),
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.fprule_delete,
        name="fprule_delete",
    ),
    # FP Tools
    url(r"^fptool/$", views.fptool_list, name="fptool_list"),
    url(r"^fptool/create/$", views.fptool_edit, name="fptool_create"),
    url(r"^fptool/(?P<slug>[-\w]+)/$", views.fptool_detail, name="fptool_detail"),
    url(r"^fptool/(?P<slug>[-\w]+)/edit/$", views.fptool_edit, name="fptool_edit"),
    # FP Commands
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/$",
        views.fpcommand_detail,
        name="fpcommand_detail",
    ),
    url(r"^fpcommand/create/$", views.fpcommand_edit, name="fpcommand_create"),
    url(r"^fpcommand/(?P<usage>[-\w]+)/$", views.fpcommand_list, name="fpcommand_list"),
    url(r"^fpcommand/$", views.fpcommand_list, name="fpcommand_list"),
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.fpcommand_edit,
        name="fpcommand_edit",
    ),
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.fpcommand_delete,
        name="fpcommand_delete",
    ),
    # Revisions
    url(
        r"^revisions/(?P<entity_name>[-\w]+)/(?P<uuid>" + UUID_REGEX + ")/$",
        views.revision_list,
        name="revision_list",
    ),
]

src/dashboard/src/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url, include
from django.conf import settings


urlpatterns = [
    url(r"^mcp/", include("components.mcp.urls")),
    url(r"^installer/", include("installer.urls")),
    url(r"^administration/accounts/", include("components.accounts.urls")),
    url(r"^archival-storage/", include("components.archival_storage.urls")),
    url(r"^fpr/", include("fpr.urls")),
    url(
        r"^(?P<unit_type>transfer|ingest)/", include("components.unit.urls")
    ),  # URLs common to transfer & ingest
    url(
        r"^transfer/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.transfer_urls"),
    ),
    url(r"^transfer/", include("components.transfer.urls")),
    url(r"^appraisal/", include("components.appraisal.urls")),
    url(
        r"^ingest/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.ingest_urls"),
    ),
    url(r"^ingest/", include("components.ingest.urls")),
    url(r"^administration/", include("components.administration.urls")),
    url(r"^filesystem/", include("components.filesystem_ajax.urls")),
    url(r"^api/", include("components.api.urls")),
    url(r"^file/", include("components.file.urls")),
    url(r"^access/", include("components.access.urls")),
    url(r"^backlog/", include("components.backlog.urls")),
    url(r"", include("main.urls")),
]

if settings.PROMETHEUS_ENABLED:
    # Include prometheus metrics at /metrics
    urlpatterns.append(url("", include("django_prometheus.urls")))

if settings.OIDC_AUTHENTICATION:
    urlpatterns.append(url(r"^oidc/", include("mozilla_django_oidc.urls")))

src/dashboard/src/fpr/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.urls import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _

from fpr import forms as fprforms
from fpr import models as fprmodels
from fpr import utils


CLASS_CATEGORY_MAP = {
    "format": fprmodels.Format,
    "formatgroup": fprmodels.FormatGroup,
    "idrule": fprmodels.IDRule,
    "idcommand": fprmodels.IDCommand,
    "fprule": fprmodels.FPRule,
    "fpcommand": fprmodels.FPCommand,
}


def context(variables):
    """
    This wraps a variables dict, allowing a standard set of values to be
    included in any view without explicitly defining them there.
    Any new default variables should be added to the `default` dict within
    this function.
    """
    # The categories of commands are used to populate separate browse links for
    # each category.
    default = {"categories": fprmodels.FPCommand.COMMAND_USAGE_CHOICES}
    default.update(variables)
    return default


def home(request):
    return redirect("fpr:format_list")


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def toggle_enabled(request, category, uuid):
    # TODO fix this and use it to genericize deleting things
    klass = CLASS_CATEGORY_MAP[category]
    obj = get_object_or_404(klass, uuid=uuid)
    obj.enabled = not obj.enabled
    obj.save()

    return redirect("fpr:{}_list".format(category))


# ########### FORMATS ############


def format_list(request):
    return render(
        request,
        "fpr/format/list.html",
        context(
            {
                # TODO: use paginator or something like django_datatables_view.
                "formats": fprmodels.Format.objects.get_full_list()
            }
        ),
    )


def format_detail(request, slug):
    format = get_object_or_404(fprmodels.Format, slug=slug)
    replacing_versions = [
        r[0]
        for r in fprmodels.FormatVersion.objects.filter(
            replaces__isnull=False, format=format
        ).values_list("replaces_id")
    ]
    format_versions = fprmodels.FormatVersion.objects.filter(format=format).exclude(
        uuid__in=replacing_versions
    )
    return render(request, "fpr/format/detail.html", context(locals()))


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def format_edit(request, slug=None):
    if slug:
        format = get_object_or_404(fprmodels.Format, slug=slug)
        group = format.group
        title = _("Edit format %(name)s") % {"name": format.description}
    else:
        title = _("Create format")
        format = None
        group = None
    form = fprforms.FormatForm(request.POST or None, instance=format, prefix="f")
    format_group_form = fprforms.FormatGroupForm(
        request.POST or None, instance=group, prefix="fg"
    )
    if form.is_valid():
        if form.cleaned_data["group"] == "new" and format_group_form.is_valid():
            format = form.save(commit=False)
            group = format_group_form.save()
            format.group = group
            format.save()
            messages.info(request, _("Saved."))
            return redirect("fpr:format_detail", format.slug)
        elif form.cleaned_data["group"] != "new":
            format = form.save(commit=False)
            group = fprmodels.FormatGroup.objects.get(uuid=form.cleaned_data["group"])
            format.group = group
            format = form.save()
            messages.info(request, _("Saved."))
            return redirect("fpr:format_detail", format.slug)

    return render(request, "fpr/format/form.html", context(locals()))


# ########### FORMAT VERSIONS ############


def formatversion_detail(request, format_slug, slug=None):
    format = get_object_or_404(fprmodels.Format, slug=format_slug)
    version = get_object_or_404(fprmodels.FormatVersion, slug=slug)
    utils.warn_if_viewing_disabled_revision(request, version)
    return render(request, "fpr/format/version/detail.html", context(locals()))


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def formatversion_edit(request, format_slug, slug=None):
    format = get_object_or_404(fprmodels.Format, slug=format_slug)
    if slug:
        version = get_object_or_404(fprmodels.FormatVersion, slug=slug, format=format)
        title = _("Replace format version %(name)s") % {"name": version.description}
    else:
        version = None
        title = _("Create format version")
    form = fprforms.FormatVersionForm(request.POST or None, instance=version)
    if form.is_valid():
        # If replacing, disable old one and set replaces info for new one
        new_version = form.save(commit=False)
        new_version.format = format
        replaces = utils.determine_what_replaces_model_instance(
            fprmodels.FormatVersion, version
        )
        new_version.save(replacing=replaces)
        utils.update_references_to_object(
            fprmodels.FormatVersion, "uuid", replaces, new_version
        )
        messages.info(request, _("Saved."))
        return redirect("fpr:format_detail", format.slug)
    else:
        utils.warn_if_replacing_with_old_revision(request, version)

    return render(request, "fpr/format/version/form.html", context(locals()))


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def formatversion_delete(request, format_slug, slug):
    format = get_object_or_404(fprmodels.Format, slug=format_slug)
    version = get_object_or_404(fprmodels.FormatVersion, slug=slug, format=format)
    dependent_objects = utils.dependent_objects(version)
    breadcrumbs = [
        {"text": _("Format versions"), "link": reverse("fpr:format_list")},
        {
            "text": format.description,
            "link": reverse("fpr:format_detail", args=[format.slug]),
        },
    ]
    if request.method == "POST":
        if "disable" in request.POST:
            version.enabled = False
            messages.info(request, _("Disabled."))
            for obj in dependent_objects:
                obj["value"].enabled = False
                obj["value"].save()
        if "enable" in request.POST:
            version.enabled = True
            messages.info(request, _("Enabled."))
        version.save()
        return redirect("fpr:format_detail", format.slug)
    return render(
        request,
        "fpr/disable.html",
        context(
            {
                "breadcrumbs": breadcrumbs,
                "dependent_objects": dependent_objects,
                "form_url": reverse(
                    "fpr:formatversion_delete", args=[format.slug, version.slug]
                ),
                "toggle_label": _("Enable/disable format version"),
                "object": version,
            }
        ),
    )


# ########### FORMAT GROUPS ############


def formatgroup_list(request):
    groups = fprmodels.FormatGroup.objects.all()
    return render(request, "fpr/format/group/list.html", context(locals()))


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def formatgroup_edit(request, slug=None):
    if slug:
        group = get_object_or_404(fprmodels.FormatGroup, slug=slug)
        group_formats = fprmodels.Format.objects.filter(group=group.uuid)
        title = _("Edit format group %(name)s") % {"name": group.description}
    else:
        title = _("Create format group")
        group = None

    form = fprforms.FormatGroupForm(request.POST or None, instance=group)
    if form.is_valid():
        group = form.save()
        messages.info(request, "Saved.")
        return redirect("fpr:formatgroup_list")

    return render(request, "fpr/format/group/form.html", context(locals()))


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def formatgroup_delete(request, slug):
    group = get_object_or_404(fprmodels.FormatGroup, slug=slug)
    format_count = fprmodels.Format.objects.filter(group=group.uuid).count()
    other_groups = fprmodels.FormatGroup.objects.exclude(uuid=group.uuid)
    other_group_count = len(other_groups)
    if request.method == "POST":
        if "delete" in request.POST:
            # if formats exist that are a member of this group, perform group substitution
            formats = fprmodels.Format.objects.filter(group=group.uuid)
            if (len(formats)) > 0:
                substitute_group_uuid = request.POST.get("substitute", "")
                if "substitute" in request.POST and substitute_group_uuid != "":
                    substitute_group = fprmodels.FormatGroup.objects.get(
                        uuid=substitute_group_uuid
                    )
                    substitution_count = 0
                    for format in formats:
                        format.group = substitute_group
                        format.save()
                        substitution_count += 1
                    messages.info(
                        request,
                        _("%(count)d substitutions were performed.")
                        % {"count": str(substitution_count)},
                    )
                else:
                    messages.warning(
                        request,
                        _(
                            "Please select a group to substitute for this group in member formats."
                        ),
                    )
                    return redirect("fpr:formatgroup_delete", slug)
            group.delete()
            messages.info(request, _("Deleted."))
        return redirect("fpr:formatgroup_list")
    else:
        return render(request, "fpr/format/group/delete.html", context(locals()))


# ########### ID TOOLS ############


def idtool_list(request):
    idtools = fprmodels.IDTool.objects.filter(enabled=True)
    return render(request, "fpr/idtool/list.html", context(locals()))

src/dashboard/src/fpr/templates/fpr/fprule/detail.html
{% extends "fpr/app_layout.html" %}
{% load i18n %}
{% load revisions_link %}

{% block title %}{{ block.super }} - {% blocktrans with description=fprule.purpose|title %}Rule {{ description }}{% endblocktrans %}{% endblock title %}
{% block page_title %}{% blocktrans with description=fprule.purpose|title %}Rule {{ description }}{% endblocktrans %}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'fpr:fprule_list' usage %}">{% trans "Format policy rules" %}</a></li>
<li>{% blocktrans with description=fprule.purpose|title %}Rule {{ description }}{% endblocktrans %}</li>
{% endblock breadcrumbs %}

{% block app_content %}

<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

    {% revisions_link "fprule" fprule.uuid %}

    <div class='format'>
      <dl>
        <dt>{% trans "UUID" %}</dt>
        <dd>{{ fprule.uuid }}</dd>
        <dt>{% trans "Purpose" %}</dt>
        <dd>{{ fprule.get_purpose_display }} Rule</dd>
        <dt>{% trans "Format" %}</dt>
        <dd><a href="{% url 'fpr:formatversion_detail' fprule.format.format.slug fprule.format.slug %}">{{ fprule.format.description }}</a></dd>
        <dt>{% trans "Command" %}</dt>
        <dd><a href="{% url 'fpr:fpcommand_detail' fprule.command.uuid %}">{{ fprule.command.description }}</a></dd>
        <dt>{% trans "Stats" %}</dt>
        <dd>{% blocktrans with count=fprule.count_okay %}Success: {{ count }}{% endblocktrans %}</dd>
        <dd>{% blocktrans with count=fprule.count_not_okay %}Failure: {{ count }}{% endblocktrans %}</dd>
        <dd>{% blocktrans with count=fprule.count_attempts %}Total: {{ count }}{% endblocktrans %}</dd>
        <dt>{% trans "Enabled" %}</dt>
        <dd>{{ fprule.enabled|yesno:_('Yes,No') }}</dd>
        {% if request.user.is_superuser %}
        <dt>{% trans "Actions" %}</dt>
        <dd><a href="{% url 'fpr:fprule_edit' fprule.uuid %}">{% trans "Replace" %}</a></dd>
        <dd><a href="{% url 'fpr:fprule_delete' fprule.uuid %}">{{ fprule.enabled|yesno:_("Disable,Enable") }}</a></dd>
        {% endif %}
      </dl>
    </div>

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}

src/dashboard/src/fpr/templates/fpr/fprule/form.html
{% extends "fpr/app_layout.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}{{ block.super }} - {{ title }}{% endblock title %}
{% block page_title %}{{ title }}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'fpr:fprule_list' %}">{% trans "Format policy rules" %}</a></li>
<li>{{ title }}</li>
{% endblock breadcrumbs %}

{% block app_content %}

<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

    <div class='tool'>
      {% if fprule %}
        <form action="{% url 'fpr:fprule_edit' fprule.uuid %}" method="post">
      {% else %}
        <form action="{% url 'fpr:fprule_create' %}" method="post">
      {% endif %}

      {% csrf_token %}
      {{ form|as_bootstrap }}

      {% if fprule %}
      <form action="{% url 'fpr:fprule_edit' fprule.uuid %}" method="post" id='fprule_form'>
      {% else %}
      <form action="{% url 'fpr:fprule_create' %}" method="post" id='fprule_form'>
      {% endif %}

        {% csrf_token %}

        <div id='fprule_command_form'>
          {{ fprule_command_form|as_bootstrap }}
        </div>
        <p>
          {{ form.description.errors }}
          {{ form.description.label_tag }} {{ form.description }}
        </p>
        <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" />
      </form>
    </div>

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}

{% block extra_js %}
<script type="text/javascript">

function display_extra_form() {
  val = $("#id_f-command option:selected").val();
  if (val == 'new') {
    $('#fprule_command_form').show();
  } else {
    $('#fprule_command_form').hide();
  }
}

$(document).ready(function () {
  display_extra_form();
  $("#id_f-command").change(function () {display_extra_form();});

});

</script>
{% endblock %}

src/dashboard/src/fpr/templates/fpr/fprule/list.html
{% extends "fpr/app_layout.html" %}
{% load i18n %}

{% block title %}{{ block.super }} - {% trans "Format policy rules " %}{% endblock title %}
{% block page_title %}{% trans "Format policy rules " %}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li>{% trans "Format policy rules " %}</li>
<li>{% trans "List" %}</li>
{% endblock breadcrumbs %}

{% block app_content %}

<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

    {% if request.user.is_superuser %}
    <p><a href="{% url 'fpr:fprule_create' %}">{% trans 'Create new rule' %}</a></p>
    {% endif %}

    {% if fprules %}
      <table class="datatable">
        <thead>
          <tr>
            <th>{% trans "Purpose" %}</th>
            <th>{% trans "Format" %}</th>
            <th>{% trans "Command" %}</th>
            <th>{% trans "Success" %}</th>
            <th>{% trans "Enabled" %}</th>
            <th>{% trans "Actions" %}</th>
          </tr>
        </thead>
        <tbody>
        {% for fprule in fprules %}
          <tr>
            <td><a href="{% url 'fpr:fprule_detail' fprule.uuid %}">{{ fprule.get_purpose_display }}</a></td>
            <td>{{ fprule.format.description }}</td>
            <td>{{ fprule.command.description }}</td>
            <td>{{ fprule.count_okay }} out of {{ fprule.count_attempts }}</td>
            <td>{{ fprule.enabled|yesno:_('Yes,No') }}</td>
            <td>
              <a href="{% url 'fpr:fprule_detail' fprule.uuid %}">{% trans "View" %}</a>
              {% if request.user.is_superuser %}
                |
                <a href="{% url 'fpr:fprule_edit' fprule.uuid %}">{% trans "Replace" %}</a>
                |
                <a href="{% url 'fpr:fprule_delete' fprule.uuid %}">{{ fprule.enabled|yesno:_("Disable,Enable") }}</a>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{% trans "No format policy rules exist." %}</p>
    {% endif %}

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}