src/dashboard/src/fpr/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url

from fpr import views

UUID_REGEX = r"[\w]{8}(-[\w]{4}){3}-[\w]{12}"

app_name = "fpr"
urlpatterns = [
    url(r"^$", views.home, name="fpr_index"),
    url(
        r"^(?P<category>format|formatgroup|idrule|idcommand|fprule|fpcommand)/(?P<uuid>"
        + UUID_REGEX
        + ")/toggle_enabled/$",
        views.toggle_enabled,
        name="toggle_enabled",
    ),
    # Formats
    url(r"^format/$", views.format_list, name="format_list"),
    url(r"^format/create/$", views.format_edit, name="format_create"),
    url(r"^format/(?P<slug>[-\w]+)/$", views.format_detail, name="format_detail"),
    url(r"^format/(?P<slug>[-\w]+)/edit/$", views.format_edit, name="format_edit"),
    # Format Versions
    url(
        r"^format/(?P<format_slug>[-\w]+)/create/$",
        views.formatversion_edit,
        name="formatversion_create",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/$",
        views.formatversion_detail,
        name="formatversion_detail",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/edit/$",
        views.formatversion_edit,
        name="formatversion_edit",
    ),
    url(
        r"^format/(?P<format_slug>[-\w]+)/(?P<slug>[-\w]+)/delete/$",
        views.formatversion_delete,
        name="formatversion_delete",
    ),
    # Format groups
    url(r"^formatgroup/$", views.formatgroup_list, name="formatgroup_list"),
    url(r"^formatgroup/create/$", views.formatgroup_edit, name="formatgroup_create"),
    url(
        r"^formatgroup/(?P<slug>[-\w]+)/$",
        views.formatgroup_edit,
        name="formatgroup_edit",
    ),
    url(
        r"^formatgroup/delete/(?P<slug>[-\w]+)/$",
        views.formatgroup_delete,
        name="formatgroup_delete",
    ),
    # ID Tools
    url(r"^idtool/$", views.idtool_list, name="idtool_list"),
    url(r"^idtool/create/$", views.idtool_edit, name="idtool_create"),
    url(r"^idtool/(?P<slug>[-\w]+)/$", views.idtool_detail, name="idtool_detail"),
    url(r"^idtool/(?P<slug>[-\w]+)/edit/$", views.idtool_edit, name="idtool_edit"),
    # ID Rules
    url(r"^idrule/$", views.idrule_list, name="idrule_list"),
    url(r"^idrule/create/$", views.idrule_edit, name="idrule_create"),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.idrule_edit,
        name="idrule_edit",
    ),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/$",
        views.idrule_detail,
        name="idrule_detail",
    ),
    url(
        r"^idrule/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.idrule_delete,
        name="idrule_delete",
    ),
    # ID Commands
    url(r"^idcommand/$", views.idcommand_list, name="idcommand_list"),
    url(r"^idcommand/create/$", views.idcommand_edit, name="idcommand_create"),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/$",
        views.idcommand_detail,
        name="idcommand_detail",
    ),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.idcommand_edit,
        name="idcommand_edit",
    ),
    url(
        r"^idcommand/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.idcommand_delete,
        name="idcommand_delete",
    ),
    # FP Rules
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/$",
        views.fprule_detail,
        name="fprule_detail",
    ),
    url(r"^fprule/create/$", views.fprule_edit, name="fprule_create"),
    url(r"^fprule/$", views.fprule_list, name="fprule_list"),
    url(r"^fprule/(?P<usage>[-\w]+)/$", views.fprule_list, name="fprule_list"),
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.fprule_edit,
        name="fprule_edit",
    ),
    url(
        r"^fprule/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.fprule_delete,
        name="fprule_delete",
    ),
    # FP Tools
    url(r"^fptool/$", views.fptool_list, name="fptool_list"),
    url(r"^fptool/create/$", views.fptool_edit, name="fptool_create"),
    url(r"^fptool/(?P<slug>[-\w]+)/$", views.fptool_detail, name="fptool_detail"),
    url(r"^fptool/(?P<slug>[-\w]+)/edit/$", views.fptool_edit, name="fptool_edit"),
    # FP Commands
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/$",
        views.fpcommand_detail,
        name="fpcommand_detail",
    ),
    url(r"^fpcommand/create/$", views.fpcommand_edit, name="fpcommand_create"),
    url(r"^fpcommand/(?P<usage>[-\w]+)/$", views.fpcommand_list, name="fpcommand_list"),
    url(r"^fpcommand/$", views.fpcommand_list, name="fpcommand_list"),
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/edit/$",
        views.fpcommand_edit,
        name="fpcommand_edit",
    ),
    url(
        r"^fpcommand/(?P<uuid>" + UUID_REGEX + ")/delete/$",
        views.fpcommand_delete,
        name="fpcommand_delete",
    ),
    # Revisions
    url(
        r"^revisions/(?P<entity_name>[-\w]+)/(?P<uuid>" + UUID_REGEX + ")/$",
        views.revision_list,
        name="revision_list",
    ),
]

src/dashboard/src/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url, include
from django.conf import settings


urlpatterns = [
    url(r"^mcp/", include("components.mcp.urls")),
    url(r"^installer/", include("installer.urls")),
    url(r"^administration/accounts/", include("components.accounts.urls")),
    url(r"^archival-storage/", include("components.archival_storage.urls")),
    url(r"^fpr/", include("fpr.urls")),
    url(
        r"^(?P<unit_type>transfer|ingest)/", include("components.unit.urls")
    ),  # URLs common to transfer & ingest
    url(
        r"^transfer/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.transfer_urls"),
    ),
    url(r"^transfer/", include("components.transfer.urls")),
    url(r"^appraisal/", include("components.appraisal.urls")),
    url(
        r"^ingest/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.ingest_urls"),
    ),
    url(r"^ingest/", include("components.ingest.urls")),
    url(r"^administration/", include("components.administration.urls")),
    url(r"^filesystem/", include("components.filesystem_ajax.urls")),
    url(r"^api/", include("components.api.urls")),
    url(r"^file/", include("components.file.urls")),
    url(r"^access/", include("components.access.urls")),
    url(r"^backlog/", include("components.backlog.urls")),
    url(r"", include("main.urls")),
]

if settings.PROMETHEUS_ENABLED:
    # Include prometheus metrics at /metrics
    urlpatterns.append(url("", include("django_prometheus.urls")))

if settings.OIDC_AUTHENTICATION:
    urlpatterns.append(url(r"^oidc/", include("mozilla_django_oidc.urls")))

src/dashboard/src/fpr/models.py
# -*- coding: utf-8 -*-
"""
:mod:`fpr.models`

Describes the data model for the FPR

"""
from __future__ import absolute_import

import logging

from django.db import connection, models
from django.utils.translation import ugettext_lazy as _
from django.utils.six import python_2_unicode_compatible

from autoslug import AutoSlugField
from django_extensions.db.fields import UUIDField

from django.core.validators import ValidationError
from django.core.exceptions import NON_FIELD_ERRORS

logger = logging.getLogger(__name__)

# ############################## API V2 MODELS ###############################

# ########### MANAGERS ############


class Enabled(models.Manager):
    """Manager to only return enabled objects.

    Filters by enabled=True."""

    def get_queryset(self):
        return super(Enabled, self).get_queryset().filter(enabled=True)

    def get_query_set(self):
        return super(Enabled, self).get_query_set().filter(enabled=True)


# ########### MIXINS ############


class VersionedModel(models.Model):
    replaces = models.ForeignKey(
        "self",
        to_field="uuid",
        null=True,
        blank=True,
        verbose_name=_("the related model"),
        on_delete=models.CASCADE,
    )
    enabled = models.BooleanField(_("enabled"), default=True)
    lastmodified = models.DateTimeField(_("last modified"), auto_now_add=True)

    def save(self, replacing=None, *args, **kwargs):
        if replacing:
            self.replaces = replacing
            # Force it to create a new row
            self.uuid = None
            self.pk = None
            self.enabled = (
                True  # in case the version was created using an older version
            )
            replacing.enabled = False
            replacing.save()
        super(VersionedModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True

    objects = models.Manager()
    active = Enabled()


# ########### FORMATS ############


class FormatManager(models.Manager):
    def get_full_list(self):
        """Detailed list of formats including PRONOM IDs.

        This is used by ``views.format_list`` so we can return the full list of
        formats making a single query to the database. Using our initial
        dataset, we were making more than 2k queries. Looking up the PRONOM IDs
        on each result added other 2k queries.

        This approach is not ideal and it should be revisited once ``fpr``
        becomes part of the Dashboard. In the future, we could use a paginator
        or DataTables + XHR (e.g. via ``django-datatables_view``). Currently,
        it is hard to make changes like this because of they way that templates
        and JavaScript code is arranged. This is a temporary fix!
        """
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT
                    fpr_format.id,
                    fpr_format.uuid,
                    fpr_format.description,
                    fpr_format.slug,
                    fpr_formatgroup.slug AS group_slug,
                    fpr_formatgroup.description AS group_name,
                    group_concat(fpr_formatversion.pronom_id) AS pronom_ids
                FROM fpr_format
                LEFT JOIN fpr_formatgroup
                    ON (fpr_format.group_id = fpr_formatgroup.uuid)
                LEFT JOIN fpr_formatversion
                    ON (fpr_format.uuid = fpr_formatversion.format_id
                        AND fpr_formatversion.pronom_id != "")
                GROUP BY fpr_format.id;
            """
            )
            ret = []
            for row in cursor.fetchall():
                # Include PRONOM IDs (up to three) in the format description.
                description = row[2]
                pronom_ids = row[6]
                if pronom_ids:
                    pronom_ids = pronom_ids.split(",")
                    if len(pronom_ids) > 3:
                        pronom_ids = pronom_ids[:3]
                        pronom_ids.append("...")
                    description = "{} ({})".format(description, ", ".join(pronom_ids))
                # Hydrate model.
                m = self.model(
                    id=row[0], uuid=row[1], description=description, slug=row[3]
                )
                m.group_slug = row[4]
                m.group_name = row[5]
                ret.append(m)
            return ret


@python_2_unicode_compatible
class Format(models.Model):
    """User-friendly description of format.

    Collects multiple related FormatVersions to one conceptual version.

    Eg. GIF, Word file."""

    uuid = UUIDField(
        editable=False, unique=True, version=4, help_text=_("Unique identifier")
    )
    description = models.CharField(
        _("description"), max_length=128, help_text=_("Common name of format")
    )
    group = models.ForeignKey(
        "FormatGroup",
        to_field="uuid",
        null=True,
        verbose_name=_("the related group"),
        on_delete=models.CASCADE,
    )
    slug = AutoSlugField(_("slug"), populate_from="description", unique=True)

    objects = FormatManager()

    class Meta:
        verbose_name = _("Format")
        ordering = ["group", "description"]

    def __str__(self):
        return u"{}: {}".format(self.group.description, self.description)


@python_2_unicode_compatible
class FormatGroup(models.Model):
    """ Group/classification for formats.  Eg. image, video, audio. """

    uuid = UUIDField(
        editable=False, unique=True, version=4, help_text=_("Unique identifier")
    )
    description = models.CharField(_("description"), max_length=128)
    slug = AutoSlugField(_("slug"), populate_from="description", unique=True)

    class Meta:
        verbose_name = _("Format group")
        ordering = ["description"]

    def __str__(self):
        return u"{}".format(self.description)


@python_2_unicode_compatible
class FormatVersion(VersionedModel, models.Model):
    """ Format that a tool identifies. """

    uuid = UUIDField(
        editable=False, unique=True, version=4, help_text=_("Unique identifier")
    )
    format = models.ForeignKey(
        "Format",
        to_field="uuid",
        related_name="version_set",
        null=True,
        verbose_name=_("the related format"),
        on_delete=models.CASCADE,
    )
    version = models.CharField(_("version"), max_length=10, null=True, blank=True)
    pronom_id = models.CharField(_("pronom id"), max_length=32, null=True, blank=True)
    description = models.CharField(
        _("description"),
        max_length=128,
        null=True,
        blank=True,
        help_text=_("Formal name to go in the METS file."),
    )
    access_format = models.BooleanField(_("access format"), default=False)
    preservation_format = models.BooleanField(_("preservation format"), default=False)

    slug = AutoSlugField(
        populate_from="description", unique_with="format", always_update=True
    )

    class Meta:
        verbose_name = _("Format version")
        ordering = ["format", "description"]

    def validate_unique(self, *args, **kwargs):
        super(FormatVersion, self).validate_unique(*args, **kwargs)

        if len(self.pronom_id) > 0:
            qs = self.__class__._default_manager.filter(
                pronom_id=self.pronom_id, enabled=1
            )

            if not self._state.adding and self.pk is not None:
                qs = qs.exclude(pk=self.pk)

            if qs.exists():
                raise ValidationError(
                    {
                        NON_FIELD_ERRORS: [
                            _(
                                "Unable to save, an active Format Version  with this pronom id already exists."
                            )
                        ]
                    }
                )

    def __str__(self):
        return _("%(format)s: %(description)s (%(pronom_id)s)") % {
            "format": self.format,
            "description": self.description,
            "pronom_id": self.pronom_id,
        }


# ########### ID TOOLS ############


@python_2_unicode_compatible
class IDCommand(VersionedModel, models.Model):
    """Command to run an IDToolConfig and parse the output.

    IDCommand runs 'script' (which runs an IDTool with a specific IDToolConfig)
    and parses the output."""

    uuid = UUIDField(
        editable=False, unique=True, version=4, help_text=_("Unique identifier")
    )
    description = models.CharField(
        _("description"), max_length=256, help_text=_("Name to identify script")
    )
    CONFIG_CHOICES = (
        ("PUID", _("PUID")),
        ("MIME", _("MIME type")),
        ("ext", _("File extension")),
    )
    config = models.CharField(_("configuration"), max_length=4, choices=CONFIG_CHOICES)

    script = models.TextField(_("script"), help_text=_("Script to be executed."))
    SCRIPT_TYPE_CHOICES = (
        ("bashScript", _("Bash script")),
        ("pythonScript", _("Python script")),
        ("command", _("Command line")),
        ("as_is", _("No shebang needed")),
    )
    script_type = models.CharField(
        _("script type"), max_length=16, choices=SCRIPT_TYPE_CHOICES
    )
    tool = models.ForeignKey(
        "IDTool",
        to_field="uuid",
        null=True,
        verbose_name=_("the related tool"),
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = _("Format identification command")
        ordering = ["description"]

    def __str__(self):
        return _("%(tool)s %(config)s runs %(command)s") % {
            "tool": self.tool,
            "config": self.get_config_display(),
            "command": self.description,
        }

    def save(self, *args, **kwargs):
        """Override save() to ensure that only one command is enabled."""
        if self.enabled:
            try:
                cmd = IDCommand.objects.get(enabled=True)
            except IDCommand.DoesNotExist:

src/dashboard/src/fpr/templates/fpr/idcommand/detail.html
{% extends "fpr/app_layout.html" %}
{% load i18n %}
{% load revisions_link %}

{% block title %}{{ block.super }} - {% blocktrans with description=idcommand.description %}Identification command {{ description }}{% endblocktrans %}{% endblock title %}
{% block page_title %}{% blocktrans with description=idcommand.description %}Identification command {{ description }}{% endblocktrans %}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'fpr:idcommand_list' %}">{% trans "Identification commands" %}</a></li>
<li>{{ idcommand.description }}</li>
{% endblock breadcrumbs %}

{% block app_content %}

<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

    {% revisions_link "idcommand" idcommand.uuid %}

    <div class='format'>
      <dl>
        <dt>{% trans "UUID" %}</dt>
          <dd>{{ idcommand.uuid }}</dd>
        <dt>{% trans "Tool" %}</dt>
          <dd>{{ idcommand.tool }}
        <dt>{% trans "Description" %}</dt>
          <dd>{{ idcommand.description }}</dd>
        <dt>{% trans "Mode" %}</dt>
          <dd>{{ idcommand.config }}</dd>
        <dt>{% trans "Script" %}</dt>
          <dd><pre>{{ idcommand.script }}</pre></dd>
        <dt>{% trans "Script type" %}</dt>
          <dd>{{ idcommand.get_script_type_display }}</dd>
        <dt>{% trans "Enabled" %}</dt>
          <dd>{{ idcommand.enabled|yesno:_('Yes,No') }}</dd>
        {% if request.user.is_superuser %}
        <dt>{% trans "Actions" %}</dt>
          <dd><a href="{% url 'fpr:idcommand_edit' idcommand.uuid %}">{% trans "Replace" %}</a></dd>
          <dd><a href="{% url 'fpr:idcommand_delete' idcommand.uuid %}">{{ idcommand.enabled|yesno:_("Disable,Enable") }}</a></dd>
        {% endif %}
      </dl>
    </div>

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}

src/dashboard/src/fpr/templates/fpr/idcommand/form.html
{% extends "fpr/app_layout.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}{{ block.super }} - {{ title }}{% endblock title %}
{% block page_title %}{{ title }}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'fpr:idcommand_list' %}">{% trans "Identification commands" %}</a></li>
<li>{{ title }}</li>
{% endblock breadcrumbs %}

{% block app_content %}

<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

    <div class='tool'>
      {% if idcommand %}
        <form action="{% url 'fpr:idcommand_edit' idcommand.uuid %}" method="post">
      {% else %}
        <form action="{% url 'fpr:idcommand_create' %}" method="post">
      {% endif %}

        {% csrf_token %}
        {{ form|as_bootstrap }}

        <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" />
      </form>
    </div>

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}

src/dashboard/src/fpr/templates/fpr/idcommand/list.html
{% extends "fpr/app_layout.html" %}
{% load i18n %}

{% block title %}{{ block.super }} - {% trans "Identification commands" %}{% endblock title %}
{% block page_title %}{% trans "Identification commands" %}{% endblock page_title %}

{% block breadcrumbs %}
{{ block.super }}
<li>{% trans "Identification commands" %}</li>
<li>{% trans "List" %}</li>
{% endblock breadcrumbs %}

{% block app_content %}
<div class="row">

  {% include 'fpr/_sidebar.html' %}

  <div class="col-xs-10">

  {% if request.user.is_superuser %}
  <p><a href="{% url 'fpr:idcommand_create' %}">{% trans "Create new command" %}</a></p>
  {% endif %}

{% if idcommands %}
  <table class="datatable">
    <thead>
      <tr>
        <th>{% trans 'Command' %}</th>
        <th>{% trans 'Type' %}</th>
        <th>{% trans 'Tool' %}</th>
        <th>{% trans 'Mode' %}</th>
        <th>{% trans 'Enabled' %}</th>
        <th>{% trans 'Actions' %}</th>
      </tr>
    </thead>
    <tbody>
    {% for idcommand in idcommands %}
      <tr>
        <td><a href="{% url 'fpr:idcommand_detail' idcommand.uuid %}">{{ idcommand.description }}</a></td>
        <td>{{ idcommand.get_script_type_display }}</td>
        <td><a href="{% url 'fpr:idtool_detail' idcommand.tool.slug %}">{{ idcommand.tool }}</a></td>
        <td>{{ idcommand.config }}</td>
        <td>{{ idcommand.enabled|yesno:_("Yes,No") }}</td>
        <td>
          <a href="{% url 'fpr:idcommand_detail' idcommand.uuid %}">{% trans "View" %}</a>
          {% if request.user.is_superuser %}
            | <a href="{% url 'fpr:idcommand_edit' idcommand.uuid %}">{% trans "Replace" %}</a>
            | <a href="{% url 'fpr:idcommand_delete' idcommand.uuid %}">{{ idcommand.enabled|yesno:_("Disable,Enable") }}</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>{% trans "No identification commands exist." %}</p>
{% endif %}

  </div> <!-- /col-xs-10 -->

</div> <!-- /row -->

{% endblock app_content %}