src/dashboard/src/components/api/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url
from django.conf import settings

from components.api import views

app_name = "api"
urlpatterns = [
    url(r"transfer/approve", views.approve_transfer),
    url(r"transfer/unapproved", views.unapproved_transfers),
    url(r"transfer/completed", views.completed_transfers),
    url(
        r"transfer/status/(?P<unit_uuid>" + settings.UUID_REGEX + ")",
        views.status,
        {"unit_type": "unitTransfer"},
    ),
    url(r"transfer/start_transfer/", views.start_transfer_api),
    url(r"transfer/reingest", views.reingest, {"target": "transfer"}),
    url(
        r"ingest/status/(?P<unit_uuid>" + settings.UUID_REGEX + ")",
        views.status,
        {"unit_type": "unitSIP"},
    ),
    url(r"ingest/waiting", views.waiting_for_user_input),
    url(
        r"^(?P<unit_type>transfer|ingest)/(?P<unit_uuid>"
        + settings.UUID_REGEX
        + ")/delete/",
        views.mark_hidden,
    ),
    url(r"^(?P<unit_type>transfer|ingest)/delete/", views.mark_completed_hidden),
    url(r"^ingest/reingest/approve", views.reingest_approve),
    url(r"^ingest/reingest", views.reingest, {"target": "ingest"}),
    url(r"^ingest/completed", views.completed_ingests),
    url(r"^ingest/copy_metadata_files/$", views.copy_metadata_files_api),
    url(r"administration/dips/atom/levels/$", views.get_levels_of_description),
    url(
        r"administration/dips/atom/fetch_levels/$",
        views.fetch_levels_of_description_from_atom,
        name="fetch_atom_lods",
    ),
    url(r"filesystem/metadata/$", views.path_metadata),
    url(
        r"processing-configuration/(?P<name>\w{1,16})",
        views.processing_configuration,
        name="processing_configuration",
    ),
    url(
        r"processing-configuration",
        views.processing_configurations,
        name="processing_configuration_list",
    ),
    url(r"v2beta/package", views.package),
    url(r"v2beta/validate/([-\w]+)", views.validate, name="validate"),
    url(r"v2beta/jobs/(?P<unit_uuid>" + settings.UUID_REGEX + ")", views.unit_jobs),
    url(r"v2beta/task/(?P<task_uuid>" + settings.UUID_REGEX + ")", views.task),
]

src/dashboard/src/components/file/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import

from django.conf.urls import url
from django.conf import settings

from components.file import views

app_name = "file"
urlpatterns = [
    url(r"(?P<fileuuid>" + settings.UUID_REGEX + ")/$", views.file_details),
    url(
        r"(?P<fileuuid>" + settings.UUID_REGEX + ")/tags/$",
        views.TransferFileTags.as_view(),
    ),
    url(
        r"(?P<fileuuid>" + settings.UUID_REGEX + ")/bulk_extractor/$",
        views.bulk_extractor,
    ),
]

src/dashboard/src/components/mcp/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url
from components.mcp import views

app_name = "mcp"
urlpatterns = [url(r"execute/$", views.execute), url(r"list/$", views.list)]

src/dashboard/src/components/transfer/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url
from django.conf import settings
from components.transfer import views

app_name = "transfer"
urlpatterns = [
    url(r"^$", views.grid, name="transfer_index"),
    # Transfer metadata set functions
    url(r"^create_metadata_set_uuid/$", views.create_metadata_set_uuid),
    url(
        r"^rename_metadata_set/(?P<set_uuid>"
        + settings.UUID_REGEX
        + ")/(?P<placeholder_id>[\w\-]+)/$",
        views.rename_metadata_set,
    ),
    url(
        r"^cleanup_metadata_set/(?P<set_uuid>" + settings.UUID_REGEX + ")/$",
        views.cleanup_metadata_set,
    ),
    url(r"^locations/$", views.transfer_source_locations),
    url(
        r"^component/(?P<uuid>" + settings.UUID_REGEX + ")/$",
        views.component,
        name="component",
    ),
    url(r"^status/$", views.status),
    url(r"^status/(?P<uuid>" + settings.UUID_REGEX + ")/$", views.status),
    url(
        r"^(?P<uuid>" + settings.UUID_REGEX + ")/metadata/$",
        views.transfer_metadata_list,
        name="transfer_metadata_list",
    ),
    url(
        r"^(?P<uuid>" + settings.UUID_REGEX + ")/metadata/add/$",
        views.transfer_metadata_edit,
        name="transfer_metadata_add",
    ),
    url(
        r"^(?P<uuid>" + settings.UUID_REGEX + ")/metadata/(?P<id>\d+)/$",
        views.transfer_metadata_edit,
        name="transfer_metadata_edit",
    ),
]

src/dashboard/src/components/unit/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2016 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url
from django.conf import settings

from components.unit import views

app_name = "unit"
# The first segment of these urls is '^(?P<unit_type>transfer|ingest)/'
# All views should expect a first parameter of unit_type, with a value of 'transfer' or 'ingest'
urlpatterns = [
    url(r"^(?P<unit_uuid>" + settings.UUID_REGEX + ")/$", views.detail, name="detail"),
    url(
        r"^(?P<unit_uuid>" + settings.UUID_REGEX + ")/microservices/$",
        views.microservices,
        name="microservices",
    ),
    url(r"^(?P<unit_uuid>" + settings.UUID_REGEX + ")/delete/$", views.mark_hidden),
    url(r"^delete/$", views.mark_completed_hidden),
]

src/dashboard/src/urls.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf.urls import url, include
from django.conf import settings


urlpatterns = [
    url(r"^mcp/", include("components.mcp.urls")),
    url(r"^installer/", include("installer.urls")),
    url(r"^administration/accounts/", include("components.accounts.urls")),
    url(r"^archival-storage/", include("components.archival_storage.urls")),
    url(r"^fpr/", include("fpr.urls")),
    url(
        r"^(?P<unit_type>transfer|ingest)/", include("components.unit.urls")
    ),  # URLs common to transfer & ingest
    url(
        r"^transfer/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.transfer_urls"),
    ),
    url(r"^transfer/", include("components.transfer.urls")),
    url(r"^appraisal/", include("components.appraisal.urls")),
    url(
        r"^ingest/(?P<uuid>" + settings.UUID_REGEX + ")/rights/",
        include("components.rights.ingest_urls"),
    ),
    url(r"^ingest/", include("components.ingest.urls")),
    url(r"^administration/", include("components.administration.urls")),
    url(r"^filesystem/", include("components.filesystem_ajax.urls")),
    url(r"^api/", include("components.api.urls")),
    url(r"^file/", include("components.file.urls")),
    url(r"^access/", include("components.access.urls")),
    url(r"^backlog/", include("components.backlog.urls")),
    url(r"", include("main.urls")),
]

if settings.PROMETHEUS_ENABLED:
    # Include prometheus metrics at /metrics
    urlpatterns.append(url("", include("django_prometheus.urls")))

if settings.OIDC_AUTHENTICATION:
    urlpatterns.append(url(r"^oidc/", include("mozilla_django_oidc.urls")))

src/dashboard/src/components/accounts/views.py
# -*- coding: utf-8 -*-
# This file is part of Archivematica.
#
# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import absolute_import

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext as _

from tastypie.models import ApiKey

from components.accounts.forms import UserCreationForm, UserProfileForm
from components.accounts.forms import UserChangeForm
from components.accounts.forms import ApiKeyForm
import components.decorators as decorators
from components.helpers import generate_api_key
from main.models import UserProfile


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def list(request):
    users = User.objects.all()
    return render(request, "accounts/list.html", locals())


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
def add(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        userprofileform = UserProfileForm(request.POST)
        if form.is_valid():
            newuser = form.save(commit=False)
            newuser.is_staff = True
            newuser.save()
            api_key = ApiKey.objects.create(user=newuser)
            api_key.key = api_key.generate_key()
            api_key.save()
            user_profile = UserProfile.objects.get(user=newuser)
            userprofileform = UserProfileForm(request.POST, instance=user_profile)
            userprofileform.save()

            messages.info(request, _("Saved."))
            return redirect("accounts:accounts_index")
    else:
        # Clearing out values that are getting inherited from currently logged in user
        data = {"email": ""}
        form = UserCreationForm(initial=data)
        userprofileform = UserProfileForm()

    return render(
        request, "accounts/add.html", {"form": form, "userprofileform": userprofileform}
    )


def profile(request):
    # If users are editable in this setup, go to the editable profile view
    if settings.ALLOW_USER_EDITS:
        return edit(request)

    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    title = _("Your profile (%s)") % user

    if request.method == "POST":
        form = ApiKeyForm(request.POST)
        userprofileform = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid() and userprofileform.is_valid():
            if form["regenerate_api_key"] != "":
                generate_api_key(user)
            userprofileform.save()

            return redirect("accounts:profile")
    else:
        form = ApiKeyForm()
        userprofileform = UserProfileForm(instance=user_profile)

    return render(
        request,
        "accounts/profile.html",
        {"form": form, "userprofileform": userprofileform, "title": title},
    )


def edit(request, id=None):
    # Forbidden if user isn't an admin and is trying to edit another user
    if str(request.user.id) != str(id) and id is not None:
        if request.user.is_superuser is False:
            return redirect("main:forbidden")

    # Load user
    if id is None:
        user = request.user
        title = "Edit your profile (%s)" % user
    else:
        user = get_object_or_404(User, pk=id)
        title = "Edit user %s" % user

    user_profile = UserProfile.objects.get(user=user)

    # Form
    if request.method == "POST":
        form = UserChangeForm(request.POST, instance=user)
        userprofileform = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid() and userprofileform.is_valid():
            user = form.save(commit=False)

            # change password if requested
            password = request.POST.get("password", "")
            if password != "":
                user.set_password(password)

            # prevent non-admin from self-promotion
            if not request.user.is_superuser:
                user.is_superuser = False

            user.save()
            userprofileform.save()

            # regenerate API key if requested
            regenerate_api_key = request.POST.get("regenerate_api_key", "")
            if regenerate_api_key != "":
                generate_api_key(user)

            # determine where to redirect to
            if request.user.is_superuser:
                return_view = "accounts:accounts_index"
            else:
                return_view = "accounts:profile"

            messages.info(request, _("Saved."))
            return redirect(return_view)
    else:
        suppress_administrator_toggle = True
        if request.user.is_superuser:
            suppress_administrator_toggle = False
        form = UserChangeForm(
            instance=user, suppress_administrator_toggle=suppress_administrator_toggle
        )
        userprofileform = UserProfileForm(instance=user_profile)

    return render(
        request,
        "accounts/edit.html",
        {
            "form": form,
            "userprofileform": userprofileform,
            "user": user,
            "title": title,
        },
    )


def delete_context(request, id):
    user = User.objects.get(pk=id)
    prompt = "Delete user " + user.username + "?"
    cancel_url = reverse("accounts:accounts_index")
    return {"action": "Delete", "prompt": prompt, "cancel_url": cancel_url}


@user_passes_test(lambda u: u.is_superuser, login_url="/forbidden/")
@decorators.confirm_required("simple_confirm.html", delete_context)
def delete(request, id):
    # Security check
    if request.user.id != id:
        if request.user.is_superuser is False:
            return redirect("main:forbidden")
    # Avoid removing the last user
    if 1 == User.objects.count():
        return redirect("main:forbidden")
    # Delete
    try:
        user = User.objects.get(pk=id)
        if request.user.username == user.username:
            raise Http404
        user.delete()
        return redirect("accounts:accounts_index")
    except:
        raise Http404

src/dashboard/src/templates/transfer/component.html
{% extends "layout_fluid.html" %}
{% load breadcrumb %}
{% load i18n %}
{% load keyvalue %}

{% block content %}
  <div class="row">
    <div class="col-md-12">

      {% trans "Transfer" as transfer_label %}
      {% trans "Component metadata" as rights_label %}

      <ul class="breadcrumb">
        {% breadcrumb_url transfer_label 'transfer:transfer_index' %}
        {% breadcrumb component_metadata_label %}
      </ul>

      <form method='POST'>
      {% csrf_token %}
      <input name='path' type='hidden' value='{{ path }}'/>
      <table class="table">
      {% for field in fields %}
        <tr>
          <td>
            <label>{{ field.fieldlabel }}</label>
          </td>
          <td>
            {% if field.fieldtype == 'text' %}
              <input name='{{ field.fieldname }}' value='{{ values|keyvalue:field.fieldname }}' />
            {% endif %}

            {% if field.fieldtype == 'textarea' %}
              <textarea name='{{ field.fieldname }}'>{{ values|keyvalue:field.fieldname }}</textarea>
            {% endif %}

            {% if field.fieldtype == 'select' %}
              <select name='{{ field.fieldname }}'>
                {% with values|keyvalue:field.fieldname as select_value %}
                  {% for optiondata in options %}
                    {% if optiondata.field == field %}
                      {% for option in optiondata.options %}
                        <option {% if option == select_value %}selected{% endif %}>{{ option }}</option>
                      {% endfor %}
                    {% endif %}
                  {% endfor %}
                {% endwith %}
              </select>

            {% endif %}
          </td>
        </tr>
      {% endfor %}
        <tr>
          <td colspan=2>
            <input type='submit' value='{% trans "Save" %}' />
          </td>
        </tr>
      </table>
      </form>

    </div>
  </div>
{% endblock %}

src/dashboard/src/templates/transfer/detail.html
{% extends "layout_fluid.html" %}
{% load breadcrumb %}
{% load i18n %}

{% block content %}
  <div class="row">
    <div class="col-md-12">

      {% trans "Transfer" as transfer_label %}

      <ul class="breadcrumb">
        {% breadcrumb_url transfer_label 'transfer:transfer_index' %}
        {% breadcrumb name %}
      </ul>

      <h1>
        {{ transfer_label }}<br />
        <small>{{ name }}</small>
      </h1>

      <p>
        {% blocktrans with uuid=uuid %}
          <strong>UUID:</strong> {{ uuid }}
        {% endblocktrans %}
      </p>

      {% if is_waiting %}
        <div class="alert alert-info block-message">
          <p>{% trans "There are microservices awaiting user decisions." %}</p>
          <div class="alert-actions">
            <a class="btn btn-sm" href="{% url 'unit:microservices' unit_type uuid %}">{% trans "View microservices" %}</a>
          </div>
        </div>
      {% endif %}

      <h5>{% trans "Microservices" %}</h5>
      <ul>
        <li><a href="{% url 'unit:microservices' unit_type uuid %}">{% trans "List" %}</a></li>
      </ul>

      <h5>{% trans "Rights" %}</h5>
      <ul>
        <li><a href="{% url 'rights_transfer:index' uuid %}">{% trans "List" %}</a></li>
        <li><a href="{% url 'rights_transfer:add' uuid %}">{% trans "Add" %}</a></li>
      </ul>

      {% if set_uuid %}
        <h5>{% trans "Transfer metadata" %}</h5>
        <ul>
          <li><a href="{% url 'transfer:component' set_uuid %}">{% trans "Edit" %}</a></li>
        </ul>
      {% endif %}

      <h5>{% trans "Metadata" %}</h5>
      <ul>
        <li><a href="{% url 'transfer:transfer_metadata_list' uuid %}">{% trans "List" %}</a></li>
        <li><a href="{% url 'transfer:transfer_metadata_add' uuid %}">{% trans "Add" %}</a></li>
      </ul>

    </div>
  </div>
{% endblock %}

src/dashboard/src/templates/transfer/metadata_edit.html
{% extends "layout_fluid.html" %}
{% load breadcrumb %}
{% load i18n %}
{% load static %}

{% block js %}
  <script type="text/javascript" src="{% static 'js/contextual_help.js' %}"></script>
{% endblock %}

{% block content %}
<style>
#contextual_help {
  width: 220px;
  background-color: #eee;
  padding: 1em;
  position: absolute;
  left: 700px;
}
</style>

<script>
$(document).ready(function() {
  archivematicaEnableContextualHelp();
});
</script>

  <div class="row">
    <div class="col-md-12">

      {% trans "Transfer" as transfer_label %}
      {% trans "Metadata" as metadata_label %}
      {% trans "Edit" as edit_label %}
      {% trans "Add" as add_label %}

      <ul class="breadcrumb">
        {% breadcrumb_url transfer_label 'transfer:transfer_index' %}
        {% breadcrumb_url name 'unit:detail' 'transfer' uuid %}
        {% breadcrumb_url metadata_label 'transfer:transfer_metadata_list' uuid %}
        {% if id %}
          {% breadcrumb edit_label %}
        {% else %}
          {% breadcrumb add_label %}
        {% endif %}
      </ul>

      <h1>
        {{ metadata_label }}<br />
        <small>{{ name }}</small>
      </h1>

      {% if id %}
        <form class="form-stacked" method="post" action="{% url 'transfer:transfer_metadata_edit' uuid id %}">
      {% else %}
        <form class="form-stacked" method="post" action="{% url 'transfer:transfer_metadata_add' uuid %}">
      {% endif %}

        {% csrf_token %}
        {% include "_form.html" %}

        <div class="actions">
          {% if id %}
            <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}" />
          {% else %}
            <input type="submit" class="btn btn-primary" value="{% trans 'Create' %}" />
          {% endif %}
          <a href="{% url 'transfer:transfer_metadata_list' uuid %}" class="btn btn-default">{% trans "Cancel" %}</a>
        </div>

      </form>

    </div>
  </div>

  <!-- define contextual help -->

  <div id='id_title_help' style='display:none'>
    <p>{% trans "A name given to the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_creator_help' style='display:none'>
    <p>{% trans "An entity primarily responsible for making the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_subject_help' style='display:none'>
    <p>{% trans "The topic of the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_description_help' style='display:none'>
    <p>{% trans "An account of the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_publisher_help' style='display:none'>
    <p>{% trans "An entity responsible for making the resource available." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_contributor_help' style='display:none'>
    <p>{% trans "An entity responsible for making contributions to the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_date_help' style='display:none'>
    <p>{% trans "A point or period of time associated with an event in the lifecycle of the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_type_help' style='display:none'>
    <p>
      {% trans "The nature or genre of the resource." %}
      (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)
      {% blocktrans %}
        You may wish to use the DCMI type vocabulary provided here: <a href="http://dublincore.org/documents/dcmi-type-vocabulary/">http://dublincore.org/documents/dcmi-type-vocabulary/</a>
      {% endblocktrans %}
    </p>
  </div>

  <div id='id_format_help' style='display:none'>
    <p>
      {% trans "The file format, physical medium, or dimensions of the resource." %}
      (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)
      {% blocktrans %}
        Best practice is to use a controlled vocabulary such as the list of Internet Media Types [MIME] provided here: <a href="http://www.iana.org/assignments/media-types/" target="_blank">http://www.iana.org/assignments/media-types/</a>
      {% endblocktrans %}
    </p>
  </div>

  <div id='id_identifier_help' style='display:none'>
    <p>{% trans "An unambiguous reference to the resource within a given context." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_source_help' style='display:none'>
    <p>{% trans "A related resource from which the described resource is derived." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_relation_help' style='display:none'>
    <p>{% trans "A related resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_language_help' style='display:none'>
    <p>{% trans "A language of the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_coverage_help' style='display:none'>
    <p>{% trans "The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

  <div id='id_rights_help' style='display:none'>
    <p>{% trans "Information about rights held in and over the resource." %} (<a href="http://dublincore.org/documents/dces/" target="_blank">ISO15836</a>)</p>
  </div>

{% endblock %}

src/dashboard/src/templates/transfer/metadata_list.html
{% extends "layout_fluid.html" %}
{% load breadcrumb %}

{% block content %}
  <div class="row">
    <div class="col-md-12">

      <ul class="breadcrumb">
        {% breadcrumb_url 'Transfer' 'transfer:transfer_index' %}
        {% breadcrumb_url name 'unit:detail' 'transfer' uuid %}
        {% breadcrumb 'Metadata' %}
      </ul>

      <h1>Metadata<br /><small>{{ name }}</small></h1>

      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Applies to</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for item in metadata %}
            <tr>
              <td>{{ item }}</td>
              <td>{{ name }}</td>
              <td>
                <a href='{% url 'transfer:transfer_metadata_edit' uuid item.id %}'>Edit</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="actions" style="padding-left: 1em;">
        <a class="btn btn-primary" href="{% url 'transfer:transfer_metadata_add' uuid %}">Add</a>
      </div>

    </div>
  </div>
{% endblock %}

src/dashboard/src/templates/transfer/microservices.html
{% extends "layout_fluid.html" %}
{% load breadcrumb %}
{% load i18n %}
{% load job_status %}

{% block content %}
  <div class="row">
    <div class="col-md-12">

      {% trans "Transfer" as transfer_label %}
      {% trans "Microservices" as microservices_label %}

      <ul class="breadcrumb">
        {% breadcrumb_url transfer_label 'transfer:transfer_index' %}
        {% breadcrumb_url name 'unit:detail' 'transfer' uuid %}
        {% breadcrumb microservices_label %}
      </ul>

      <h1>
        {{ microservices_label }}<br />
        <small>{{ name }}</small>
      </h1>

      {% regroup jobs by group as groups %}

      {% for item in groups %}
        <div>
          {{ item.grouper }}<br />
          <ul>
            {% for i in item.list %}
              <li>
                <strong>{{ i.description }}:</strong>
                {{ i.status|job_status }}
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endfor %}

    </div>
  </div>
{% endblock %}